### ISSUE TITLE
Dropdown - Overlap

### ISSUE THREAD

**Issue by Richasantos** [emilsgulbis/jQuery-material-form-fields#4]
Hi There,

First of all, thanks for this amazing simplistic plugin. I'm having a problem when I put 2 dropdowns close to each other. They start to overlap.

It's probably a problem related with z-index.

Can someone help on the solution?

Thanks,

**Comment by d-theus** [comment]
Seems like 

``` css
/* css/jquery.material.form.css */
.material .material-select {
    font-size: 16px;
    font-weight: 300;
    width: 100%;
    position: relative;
    margin-bottom: 10px;
    padding-top: 18px;

    /* this line: */
    z-index: 3
}
```

actually breaks things. It seems fine without this line.
